# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SAM Landing
description: >- # this means to ignore newlines until "baseurl:"
  A bare-bones landing page to allow SAM users to begin identity proofing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Login.gov
issuer: urn:gov:gsa:openidconnect.profiles:sp:sso:gsa:sam-landing
acr_values: http://idmanagement.gov/ns/assurance/ial/2
idp_host: http://localhost:3000
idp_path: /openid_connect/authorize
redirect_uri: http://localhost:3000/account
code_challenge: V2tWeJa2r0hv/Ek8BnH0COG3sjf9NIZ5gkc4C30y+vg
nonce: a671871a966400ff97d0293ed2e1568c
state: abcdefghijklmnopabcdefghijklmnop

copy_to_destination:
  - source: node_modules/uswds/dist/{js,fonts,img}
    target: assets

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
